INSERT INTO badge ( id, name, type, slug, description, multiple, awarded_count) VALUES
(1, 'Disciplined', 3, 'disciplined', 'Deleted own post with score of 3 or higher', TRUE, 0),
(2, 'Peer Pressure', 3, 'peer-pressure', 'Deleted own post with score of -3 or lower', TRUE, 0),
(3, 'Nice answer', 3, 'nice-answer', 'Answer voted up 10 times', TRUE, 0),
(4, 'Nice Question', 3, 'nice-question', 'Question voted up 10 times', TRUE, 0),
(5, 'Pundit', 3, 'pundit', 'Left 10 comments with score of 10 or more', FALSE, 0),
(6, 'Popular Question', 3, 'popular-question', 'Asked a question with 1,000 views', TRUE, 0),
(7, 'Citizen patrol', 3, 'citizen-patrol', 'First flagged post', FALSE, 0),
(8, 'Cleanup', 3, 'cleanup', 'First rollback', FALSE, 0),
(9, 'Critic', 3, 'critic', 'First down vote', FALSE, 0),
(10, 'Editor', 3, 'editor', 'First edit', FALSE, 0),
(11, 'Organizer', 3, 'organizer', 'First retag', FALSE, 0),
(12, 'Scholar', 3, 'scholar', 'First accepted answer on your own question', FALSE, 0),
(13, 'Student', 3, 'student', 'Asked first question with at least one up vote', FALSE, 0),
(14, 'Supporter', 3, 'supporter', 'First up vote', FALSE, 0),
(15, 'Teacher', 3, 'teacher', 'Answered first question with at least one up vote', FALSE, 0),
(16, 'Autobiographer', 3, 'autobiographer', 'Completed all user profile fields', FALSE, 0),
(17, 'Self-Learner', 3, 'self-learner', 'Answered your own question with at least 3 up votes', TRUE, 0),
(18, 'Great Answer', 1, 'great-answer', 'Answer voted up 100 times', TRUE, 0),
(19, 'Great Question', 1, 'great-question', 'Question voted up 100 times', TRUE, 0),
(20, 'Stellar Question', 1, 'stellar-question', 'Question favorited by 100 users', TRUE, 0),
(21, 'Famous question', 1, 'famous-question', 'Asked a question with 10,000 views', TRUE, 0),
(22, 'Alpha', 2, 'alpha', 'Actively participated in the private alpha', FALSE, 0),
(23, 'Good Answer', 2, 'good-answer', 'Answer voted up 25 times', TRUE, 0),
(24, 'Good Question', 2, 'good-question', 'Question voted up 25 times', TRUE, 0),
(25, 'Favorite Question', 2, 'favorite-question', 'Question favorited by 25 users', TRUE, 0),
(26, 'Civic duty', 2, 'civic-duty', 'Voted 300 times', FALSE, 0),
(27, 'Strunk & White', 2, 'strunk-and-white', 'Edited 100 entries', FALSE, 0),
(28, 'Generalist', 2, 'generalist', 'Active in many different tags', FALSE, 0),
(29, 'Expert', 2, 'export', 'Very active in one tag', FALSE, 0),
(30, 'Yearling', 2, 'yearling', 'Active member for a year', FALSE, 0),
(31, 'Notable Question', 2, 'notable-question', 'Asked a question with 2,500 views', TRUE, 0),
(32, 'Enlightened', 2, 'enlightened', 'First answer was accepted with at least 10 up votes', FALSE, 0),
(33, 'Beta', 2, 'beta', 'Actively participated in the private beta', FALSE, 0),
(34, 'Guru', 2, 'guru', 'Accepted answer and voted up 40 times', TRUE, 0),
(35, 'Necromancer', 2, 'necromancer', 'Answered a question more than 60 days later with at least 5 votes', TRUE, 0),
(36, 'Taxonomist', 2, 'taxonomist', 'Created a tag used by 50 questions', TRUE, 0);
