#!/bin/sh

WORKON_HOME=~/envs/osqa
PROJECT_ROOT=~/webapps/osqa_server/projects/osqa/

# activate virtual environment
. $WORKON_HOME/bin/activate

cd $PROJECT_ROOT
python manage.py once_award_badges >> $PROJECT_ROOT/log/cron_badges.log 2>&1
