#!/bin/sh

WORKON_HOME=~/envs/askbot
PROJECT_ROOT=~/webapps/askbot_server/projects/askbot/

# activate virtual environment
. $WORKON_HOME/bin/activate

cd $PROJECT_ROOT
python manage.py send_email_alerts >> $PROJECT_ROOT/log/cron_mail.log 2>&1
